In [1]:
# mappper

def mapper(centoids, point):
    pass

In [2]:
a = [[1,2,3],[4,5,6]]
b = [[4,5,6],[1,2,3]]

In [3]:
a==b

False

In [4]:
a = [1,2,3]
print('key'+'\t',a)

key	 [1, 2, 3]


In [5]:
import pandas as pd

In [6]:
import numpy as np

In [13]:
file = open('shot_logs.csv')
c = 0
for line in file.readlines():
    line = line.strip()
    line = line.split(',')
    if line[0] == 'GAME_ID':
        continue
    shot_dist = line[12]
    close_def_dist = line[18]
    shot_clock = line[9]
    player_name = line[21]
    short_status = line[14]
    def_first_name = line[16][:-1]
    def_last_name = line[15][1:]
    print(line[14])
    print(def_first_name+"----"+def_last_name)
    if shot_clock == '':
        continue
    print(line)
    datapoint = np.array([shot_dist,close_def_dist,shot_clock])
    print('player_name: ',player_name)
    print('short status:',short_status)
    print(datapoint)

    c+=1
    if c==3:
        break
    file.close()

made
 Alan----Anderson
['21400899', '"MAR 04', ' 2015 - CHA @ BKN"', 'A', 'W', '24', '1', '1', '1:09', '10.8', '2', '1.9', '7.7', '2', 'made', '"Anderson', ' Alan"', '101187', '1.3', '1', '2', 'brian roberts', '203148']
player_name:  brian roberts
short status: made
['7.7' '1.3' '10.8']
missed
 Bojan----Bogdanovic
['21400899', '"MAR 04', ' 2015 - CHA @ BKN"', 'A', 'W', '24', '2', '1', '0:14', '3.4', '0', '0.8', '28.2', '3', 'missed', '"Bogdanovic', ' Bojan"', '202711', '6.1', '0', '0', 'brian roberts', '203148']
player_name:  brian roberts
short status: missed
['28.2' '6.1' '3.4']
missed
 Bojan----Bogdanovic
missed
 Markel----Brown
['21400899', '"MAR 04', ' 2015 - CHA @ BKN"', 'A', 'W', '24', '4', '2', '11:47', '10.3', '2', '1.9', '17.2', '2', 'missed', '"Brown', ' Markel"', '203900', '3.4', '0', '0', 'brian roberts', '203148']
player_name:  brian roberts
short status: missed
['17.2' '3.4' '10.3']


In [12]:
datapoint = datapoint.astype(np.float64)

In [9]:
datapoint

array([17.2,  3.4, 10.3])

In [10]:
centroid = np.array([28.2,6.1,3.4])
centroid.shape

(3,)

In [11]:
distance = np.zeros(4)

In [12]:
distance

array([0., 0., 0., 0.])

In [13]:
from numpy.linalg import norm

In [14]:
row = norm(datapoint - centroid, axis = 0 )

In [15]:
row

13.262729734108284

In [16]:
distance[1] = np.square(row)

In [17]:
distance

array([  0. , 175.9,   0. ,   0. ])

In [18]:
a = np.argmin(distance,axis=0)

In [19]:
a = list()

In [20]:
b = np.array([0,1])

In [21]:
a.append(b)

In [22]:
a

[array([0, 1])]

In [23]:
a.append(np.array([3,3]))

In [24]:
a

[array([0, 1]), array([3, 3])]

In [25]:
a = np.array(a)

In [26]:
a

array([[0, 1],
       [3, 3]])

In [27]:
a = np.sum(a,axis=0)

In [28]:
a

array([3, 4])

In [29]:
a = np.array([1,2])
b = np.array([3,4])

In [30]:
a + b

array([4, 6])

In [31]:
dict1 = {1: 1, 2: 9, 3: 4}

In [32]:
print(dict1)

{1: 1, 2: 9, 3: 4}


In [33]:
from operator import itemgetter

In [35]:
cv = dict()

In [ ]:
file = open('shot_logs.csv')
c = 0
for line in file.readlines():
    line = line.strip()
    line = line.split(',')
    if line[0] == 'GAME_ID':
        continue
    shot_dist = line[12]
    close_def_dist = line[18]
    shot_clock = line[9]
    player_name = line[21]
    short_status = line[14]
    def_first_name = line[16][:-1]
    def_last_name = line[15][1:]
    print(line[14])
    print(def_first_name+"----"+def_last_name)
    if shot_clock == '':
        continue
    print(line)
    datapoint = np.array([shot_dist,close_def_dist,shot_clock])
    print('player_name: ',player_name)
    print('short status:',short_status)
    print(datapoint)

    c+=1
    if c==3:
        break
    file.close()